# frozen_string_literal: true
require_relative 'autobump/version'
require_relative 'autobump/config'
require_relative 'autobump/evidence'
require_relative 'autobump/runtime'
require_relative 'autobump/rewrite'
require_relative 'autobump/locate'
require_relative 'autobump/classify'
require_relative 'autobump/issue'
require_relative 'autobump/cleanup'
require_relative 'autobump/preflight'
require_relative 'autobump/distfiles'
require_relative 'autobump/artifact_diff'
require_relative 'autobump/build_test'
require_relative 'autobump/finalize'
require_relative 'autobump/pr'
require_relative 'autobump/cli'
